version: '3.8'

services:
  client-app:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/bullseyeDb
      - SPRING_DATASOURCE_USERNAME=myUser
      - SPRING_DATASOURCE_PASSWORD=myUser
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myUser
      POSTGRES_DB: bullseyeDb
    ports:
      - "5432:5432"
#    volumes:
#      - ./infrastructure/db/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
#      - db-data:/var/lib/postgresql/data
    restart: on-failure:max-retries 12

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data: